/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.scoping;

import org.eclipse.ocl.xtext.completeocl.scoping.CompleteOCLScopeProvider;

public abstract class AbstractCPLScopeProvider extends CompleteOCLScopeProvider {
}
