/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.validation;

import org.xtext.example.cpl.validation.AbstractCPLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CPLValidator extends AbstractCPLValidator {
}
