/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.cpl.parser.antlr.internal.InternalCPLParser;
import org.xtext.example.cpl.services.CPLGrammarAccess;

public class CPLParser extends AbstractAntlrParser {

	@Inject
	private CPLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCPLParser createParser(XtextTokenStream stream) {
		return new InternalCPLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TopLevelCP";
	}

	public CPLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CPLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
