/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.ui.quickfix;

import org.eclipse.ocl.xtext.essentialocl.ui.quickfix.EssentialOCLQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class CPLQuickfixProvider extends EssentialOCLQuickfixProvider {
}
