/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.cPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementA <em>Owned Element A</em>}</li>
 *   <li>{@link org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementB <em>Owned Element B</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cpl.cPL.CPLPackage#getConditionCS()
 * @model
 * @generated
 */
public interface ConditionCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Element A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Element A</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Element A</em>' attribute.
   * @see #setOwnedElementA(String)
   * @see org.xtext.example.cpl.cPL.CPLPackage#getConditionCS_OwnedElementA()
   * @model
   * @generated
   */
  String getOwnedElementA();

  /**
   * Sets the value of the '{@link org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementA <em>Owned Element A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Element A</em>' attribute.
   * @see #getOwnedElementA()
   * @generated
   */
  void setOwnedElementA(String value);

  /**
   * Returns the value of the '<em><b>Owned Element B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Element B</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Element B</em>' attribute.
   * @see #setOwnedElementB(String)
   * @see org.xtext.example.cpl.cPL.CPLPackage#getConditionCS_OwnedElementB()
   * @model
   * @generated
   */
  String getOwnedElementB();

  /**
   * Sets the value of the '{@link org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementB <em>Owned Element B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Element B</em>' attribute.
   * @see #getOwnedElementB()
   * @generated
   */
  void setOwnedElementB(String value);

} // ConditionCS
