/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.cPL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.cpl.cPL.CPLPackage
 * @generated
 */
public interface CPLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CPLFactory eINSTANCE = org.xtext.example.cpl.cPL.impl.CPLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Top Level CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top Level CP</em>'.
   * @generated
   */
  TopLevelCP createTopLevelCP();

  /**
   * Returns a new object of class '<em>Relation CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relation CP</em>'.
   * @generated
   */
  RelationCP createRelationCP();

  /**
   * Returns a new object of class '<em>Description CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description CP</em>'.
   * @generated
   */
  DescriptionCP createDescriptionCP();

  /**
   * Returns a new object of class '<em>Condition CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition CS</em>'.
   * @generated
   */
  ConditionCS createConditionCS();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CPLPackage getCPLPackage();

} //CPLFactory
