/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.cPL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.cpl.cPL.CPLFactory
 * @model kind="package"
 * @generated
 */
public interface CPLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cPL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/cpl/CPL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cPL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CPLPackage eINSTANCE = org.xtext.example.cpl.cPL.impl.CPLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.cpl.cPL.impl.TopLevelCPImpl <em>Top Level CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cpl.cPL.impl.TopLevelCPImpl
   * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getTopLevelCP()
   * @generated
   */
  int TOP_LEVEL_CP = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__NAME = 0;

  /**
   * The feature id for the '<em><b>Owned Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Owned Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_CONTEXTS = 2;

  /**
   * The feature id for the '<em><b>Owned Relation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_RELATION = 3;

  /**
   * The feature id for the '<em><b>Owned Message</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_MESSAGE = 4;

  /**
   * The number of structural features of the '<em>Top Level CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.cpl.cPL.impl.RelationCPImpl <em>Relation CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cpl.cPL.impl.RelationCPImpl
   * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getRelationCP()
   * @generated
   */
  int RELATION_CP = 1;

  /**
   * The feature id for the '<em><b>Owned Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_CP__OWNED_CONDITIONS = 0;

  /**
   * The number of structural features of the '<em>Relation CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_CP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.cpl.cPL.impl.MessageCPImpl <em>Message CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cpl.cPL.impl.MessageCPImpl
   * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getMessageCP()
   * @generated
   */
  int MESSAGE_CP = 2;

  /**
   * The feature id for the '<em><b>Owned Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CP__OWNED_EXPRESSION = 0;

  /**
   * The number of structural features of the '<em>Message CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.cpl.cPL.impl.ConditionCSImpl <em>Condition CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cpl.cPL.impl.ConditionCSImpl
   * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getConditionCS()
   * @generated
   */
  int CONDITION_CS = 3;

  /**
   * The feature id for the '<em><b>Owned Element A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_CS__OWNED_ELEMENT_A = 0;

  /**
   * The feature id for the '<em><b>Owned Element B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_CS__OWNED_ELEMENT_B = 1;

  /**
   * The number of structural features of the '<em>Condition CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_CS_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.cpl.cPL.TopLevelCP <em>Top Level CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Level CP</em>'.
   * @see org.xtext.example.cpl.cPL.TopLevelCP
   * @generated
   */
  EClass getTopLevelCP();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cpl.cPL.TopLevelCP#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.cpl.cPL.TopLevelCP#getName()
   * @see #getTopLevelCP()
   * @generated
   */
  EAttribute getTopLevelCP_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedImports <em>Owned Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Imports</em>'.
   * @see org.xtext.example.cpl.cPL.TopLevelCP#getOwnedImports()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedImports();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedContexts <em>Owned Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Contexts</em>'.
   * @see org.xtext.example.cpl.cPL.TopLevelCP#getOwnedContexts()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedContexts();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedRelation <em>Owned Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Relation</em>'.
   * @see org.xtext.example.cpl.cPL.TopLevelCP#getOwnedRelation()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedRelation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedMessage <em>Owned Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Message</em>'.
   * @see org.xtext.example.cpl.cPL.TopLevelCP#getOwnedMessage()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedMessage();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cpl.cPL.RelationCP <em>Relation CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation CP</em>'.
   * @see org.xtext.example.cpl.cPL.RelationCP
   * @generated
   */
  EClass getRelationCP();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cpl.cPL.RelationCP#getOwnedConditions <em>Owned Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Conditions</em>'.
   * @see org.xtext.example.cpl.cPL.RelationCP#getOwnedConditions()
   * @see #getRelationCP()
   * @generated
   */
  EReference getRelationCP_OwnedConditions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cpl.cPL.MessageCP <em>Message CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message CP</em>'.
   * @see org.xtext.example.cpl.cPL.MessageCP
   * @generated
   */
  EClass getMessageCP();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cpl.cPL.MessageCP#getOwnedExpression <em>Owned Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Expression</em>'.
   * @see org.xtext.example.cpl.cPL.MessageCP#getOwnedExpression()
   * @see #getMessageCP()
   * @generated
   */
  EAttribute getMessageCP_OwnedExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cpl.cPL.ConditionCS <em>Condition CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition CS</em>'.
   * @see org.xtext.example.cpl.cPL.ConditionCS
   * @generated
   */
  EClass getConditionCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementA <em>Owned Element A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Element A</em>'.
   * @see org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementA()
   * @see #getConditionCS()
   * @generated
   */
  EAttribute getConditionCS_OwnedElementA();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementB <em>Owned Element B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Element B</em>'.
   * @see org.xtext.example.cpl.cPL.ConditionCS#getOwnedElementB()
   * @see #getConditionCS()
   * @generated
   */
  EAttribute getConditionCS_OwnedElementB();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CPLFactory getCPLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.cpl.cPL.impl.TopLevelCPImpl <em>Top Level CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cpl.cPL.impl.TopLevelCPImpl
     * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getTopLevelCP()
     * @generated
     */
    EClass TOP_LEVEL_CP = eINSTANCE.getTopLevelCP();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_LEVEL_CP__NAME = eINSTANCE.getTopLevelCP_Name();

    /**
     * The meta object literal for the '<em><b>Owned Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_IMPORTS = eINSTANCE.getTopLevelCP_OwnedImports();

    /**
     * The meta object literal for the '<em><b>Owned Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_CONTEXTS = eINSTANCE.getTopLevelCP_OwnedContexts();

    /**
     * The meta object literal for the '<em><b>Owned Relation</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_RELATION = eINSTANCE.getTopLevelCP_OwnedRelation();

    /**
     * The meta object literal for the '<em><b>Owned Message</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_MESSAGE = eINSTANCE.getTopLevelCP_OwnedMessage();

    /**
     * The meta object literal for the '{@link org.xtext.example.cpl.cPL.impl.RelationCPImpl <em>Relation CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cpl.cPL.impl.RelationCPImpl
     * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getRelationCP()
     * @generated
     */
    EClass RELATION_CP = eINSTANCE.getRelationCP();

    /**
     * The meta object literal for the '<em><b>Owned Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_CP__OWNED_CONDITIONS = eINSTANCE.getRelationCP_OwnedConditions();

    /**
     * The meta object literal for the '{@link org.xtext.example.cpl.cPL.impl.MessageCPImpl <em>Message CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cpl.cPL.impl.MessageCPImpl
     * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getMessageCP()
     * @generated
     */
    EClass MESSAGE_CP = eINSTANCE.getMessageCP();

    /**
     * The meta object literal for the '<em><b>Owned Expression</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_CP__OWNED_EXPRESSION = eINSTANCE.getMessageCP_OwnedExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.cpl.cPL.impl.ConditionCSImpl <em>Condition CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cpl.cPL.impl.ConditionCSImpl
     * @see org.xtext.example.cpl.cPL.impl.CPLPackageImpl#getConditionCS()
     * @generated
     */
    EClass CONDITION_CS = eINSTANCE.getConditionCS();

    /**
     * The meta object literal for the '<em><b>Owned Element A</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_CS__OWNED_ELEMENT_A = eINSTANCE.getConditionCS_OwnedElementA();

    /**
     * The meta object literal for the '<em><b>Owned Element B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION_CS__OWNED_ELEMENT_B = eINSTANCE.getConditionCS_OwnedElementB();

  }

} //CPLPackage
