/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.cPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message CP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cpl.cPL.MessageCP#getOwnedExpression <em>Owned Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cpl.cPL.CPLPackage#getMessageCP()
 * @model
 * @generated
 */
public interface MessageCP extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Expression</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Expression</em>' attribute.
   * @see #setOwnedExpression(String)
   * @see org.xtext.example.cpl.cPL.CPLPackage#getMessageCP_OwnedExpression()
   * @model
   * @generated
   */
  String getOwnedExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.cpl.cPL.MessageCP#getOwnedExpression <em>Owned Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Expression</em>' attribute.
   * @see #getOwnedExpression()
   * @generated
   */
  void setOwnedExpression(String value);

} // MessageCP
