/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.cPL;

import org.eclipse.emf.common.util.EList;

//import org.eclipse.emf.ecore.EObject;
import org.eclipse.ocl.xtext.completeoclcs.CompleteOCLDocumentCS;
import org.eclipse.ocl.xtext.basecs.ImportCS;

import org.eclipse.ocl.xtext.completeoclcs.ContextDeclCS;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top Level CP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cpl.cPL.TopLevelCP#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedImports <em>Owned Imports</em>}</li>
 *   <li>{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedContexts <em>Owned Contexts</em>}</li>
 *   <li>{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedRelation <em>Owned Relation</em>}</li>
 *   <li>{@link org.xtext.example.cpl.cPL.TopLevelCP#getOwnedMessage <em>Owned Message</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cpl.cPL.CPLPackage#getTopLevelCP()
 * @model
 * @generated
 */
public interface TopLevelCP extends CompleteOCLDocumentCS
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cpl.cPL.CPLPackage#getTopLevelCP_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cpl.cPL.TopLevelCP#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Owned Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.ocl.xtext.basecs.ImportCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Imports</em>' containment reference list.
   * @see org.xtext.example.cpl.cPL.CPLPackage#getTopLevelCP_OwnedImports()
   * @model containment="true"
   * @generated
   */
  EList<ImportCS> getOwnedImports();

  /**
   * Returns the value of the '<em><b>Owned Contexts</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.ocl.xtext.completeoclcs.ContextDeclCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Contexts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Contexts</em>' containment reference list.
   * @see org.xtext.example.cpl.cPL.CPLPackage#getTopLevelCP_OwnedContexts()
   * @model containment="true"
   * @generated
   */
  EList<ContextDeclCS> getOwnedContexts();

  /**
   * Returns the value of the '<em><b>Owned Relation</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cpl.cPL.RelationCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Relation</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Relation</em>' containment reference list.
   * @see org.xtext.example.cpl.cPL.CPLPackage#getTopLevelCP_OwnedRelation()
   * @model containment="true"
   * @generated
   */
  EList<RelationCP> getOwnedRelation();

  /**
   * Returns the value of the '<em><b>Owned Message</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cpl.cPL.MessageCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Message</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Message</em>' containment reference list.
   * @see org.xtext.example.cpl.cPL.CPLPackage#getTopLevelCP_OwnedMessage()
   * @model containment="true"
   * @generated
   */
  EList<MessageCP> getOwnedMessage();

} // TopLevelCP
