/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.cpl.CPLRuntimeModule;
import org.xtext.example.cpl.CPLStandaloneSetup;
import org.xtext.example.cpl.ide.CPLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CPLIdeSetup extends CPLStandaloneSetup {
  @Override
  public Injector createInjector() {
    CPLRuntimeModule _cPLRuntimeModule = new CPLRuntimeModule();
    CPLIdeModule _cPLIdeModule = new CPLIdeModule();
    return Guice.createInjector(Modules2.mixin(_cPLRuntimeModule, _cPLIdeModule));
  }
}
