/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.ide;

import org.xtext.example.cpl.ide.AbstractCPLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CPLIdeModule extends AbstractCPLIdeModule {
}
