/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.cPL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.cpl.cPL.CPLPackage;
import org.xtext.example.cpl.cPL.ConditionCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Condition CS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cpl.cPL.impl.ConditionCSImpl#getOwnedElementA <em>Owned Element A</em>}</li>
 *   <li>{@link org.xtext.example.cpl.cPL.impl.ConditionCSImpl#getOwnedElementB <em>Owned Element B</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConditionCSImpl extends MinimalEObjectImpl.Container implements ConditionCS
{
  /**
   * The default value of the '{@link #getOwnedElementA() <em>Owned Element A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedElementA()
   * @generated
   * @ordered
   */
  protected static final String OWNED_ELEMENT_A_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOwnedElementA() <em>Owned Element A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedElementA()
   * @generated
   * @ordered
   */
  protected String ownedElementA = OWNED_ELEMENT_A_EDEFAULT;

  /**
   * The default value of the '{@link #getOwnedElementB() <em>Owned Element B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedElementB()
   * @generated
   * @ordered
   */
  protected static final String OWNED_ELEMENT_B_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOwnedElementB() <em>Owned Element B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedElementB()
   * @generated
   * @ordered
   */
  protected String ownedElementB = OWNED_ELEMENT_B_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConditionCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CPLPackage.Literals.CONDITION_CS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOwnedElementA()
  {
    return ownedElementA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOwnedElementA(String newOwnedElementA)
  {
    String oldOwnedElementA = ownedElementA;
    ownedElementA = newOwnedElementA;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CPLPackage.CONDITION_CS__OWNED_ELEMENT_A, oldOwnedElementA, ownedElementA));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOwnedElementB()
  {
    return ownedElementB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOwnedElementB(String newOwnedElementB)
  {
    String oldOwnedElementB = ownedElementB;
    ownedElementB = newOwnedElementB;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CPLPackage.CONDITION_CS__OWNED_ELEMENT_B, oldOwnedElementB, ownedElementB));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_A:
        return getOwnedElementA();
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_B:
        return getOwnedElementB();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_A:
        setOwnedElementA((String)newValue);
        return;
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_B:
        setOwnedElementB((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_A:
        setOwnedElementA(OWNED_ELEMENT_A_EDEFAULT);
        return;
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_B:
        setOwnedElementB(OWNED_ELEMENT_B_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_A:
        return OWNED_ELEMENT_A_EDEFAULT == null ? ownedElementA != null : !OWNED_ELEMENT_A_EDEFAULT.equals(ownedElementA);
      case CPLPackage.CONDITION_CS__OWNED_ELEMENT_B:
        return OWNED_ELEMENT_B_EDEFAULT == null ? ownedElementB != null : !OWNED_ELEMENT_B_EDEFAULT.equals(ownedElementB);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ownedElementA: ");
    result.append(ownedElementA);
    result.append(", ownedElementB: ");
    result.append(ownedElementB);
    result.append(')');
    return result.toString();
  }

} //ConditionCSImpl
