/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl;

import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.ocl.pivot.labels.ILabelGenerator;
import org.eclipse.ocl.xtext.completeocl.scoping.CompleteOCLScoping;
import org.eclipse.ocl.xtext.completeocl.utilities.CompleteOCLASResourceFactory;
import org.eclipse.ocl.xtext.completeocl.utilities.PathNameDeclCSLabelGenerator;
import org.eclipse.ocl.xtext.completeoclcs.CompleteOCLCSPackage;
import org.xtext.example.cpl.CPLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CPLStandaloneSetup extends CPLStandaloneSetupGenerated {
  private static Injector injector = null;
  
  public static void doSetup() {
    new CPLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  public static void doTearDown() {
    CPLStandaloneSetup.injector = null;
  }
  
  public static void init() {
    CompleteOCLScoping.init();
    CompleteOCLASResourceFactory.getInstance();
    EPackage.Registry.INSTANCE.put(CompleteOCLCSPackage.eNS_URI, CompleteOCLCSPackage.eINSTANCE);
    PathNameDeclCSLabelGenerator.initialize(ILabelGenerator.Registry.INSTANCE);
  }
  
  /**
   * Return the Injector for this plugin.
   */
  public static final Injector getInjector() {
    return CPLStandaloneSetup.injector;
  }
  
  @Override
  public Injector createInjector() {
    CPLStandaloneSetup.init();
    CPLStandaloneSetup.injector = super.createInjector();
    return CPLStandaloneSetup.injector;
  }
}
