/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.cpl.ui.internal.CplActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CplActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CplActivator activator = CplActivator.getInstance();
		return activator != null ? activator.getInjector(CplActivator.ORG_XTEXT_EXAMPLE_CPL_CPL) : null;
	}

}
