/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.cpl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.cpl.ui.AbstractCPLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CPLUiModule extends AbstractCPLUiModule {
  public CPLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
